### ISSUE TITLE
Cadence RPM seems to be half

### ISSUE THREAD

**Issue by MortenVinding** [arpruss/BLEBike#1]
Hi arpruss,

Your project is just what I need.

I have converted it to a platformio project in my fork here: https://github.com/MortenVinding/BLEBike.git
But it seems like the RPM counter is counting only half the revolutions.
Is this configurable on the display I haven't connected since I don't have a HD44780 display at hand?

/Morten

**Comment by arpruss** [comment]
Do you know what the RPM sensor output is like on your bike? Is it normally high, with a low spike (how long?)? Or the other way around?

**Comment by MortenVinding** [comment]
Also I only measured with a multimeter.
It’s normally high (4.29 volts if memory serves), and the low pulse seemed to be responsible long.

I will scoope that also later.
But it is precisely half of the build-in RPM display.
Changing the 60000 / in the code to 30000 / made it bang-on with the bikes computer.

**Comment by arpruss** [comment]
Why don't you add a bit of code to the interrupt handler to toggle an LED each time it detects a rotation, and then see what happens when you rotate the pedals slowly: do you miss every second one? You can also hook up a multimeter at the same time and make sure there was a signal that it missed.

It wouldn't surprise if there was some bug in my code. The ESP has trouble with triggering interrupts on a specific edge, and so I have to trigger on both edges and kludgily drop one. 

Could be the same with the heart rate.

**Comment by MortenVinding** [comment]
> Why don't you add a bit of code to the interrupt handler to toggle an LED each time it detects a rotation, and then see what happens when you rotate the pedals slowly: do you miss every second one? You can also hook up a multimeter at the same time and make sure there was a signal that it missed.

Great idea. I will do that. And also hook up my scope.


> It wouldn't surprise if there was some bug in my code. The ESP has trouble with triggering interrupts on a specific edge, and so I have to trigger on both edges and kludgily drop one.

Ahh that could also very well explain the half RPM number. So maybe for some weird reason, my ESP32 is only triggering on one of the edges.

> Could be the same with the heart rate.

Might yes. But there must also be something else going on, because it's much more off. Around 2-3 BPM when the bike registers around 70 BPM.

**Comment by arpruss** [comment]
On my bike, there are two different heart lines. There are the lines to the sensors, and you are unlikely to be able to catch anything on them without some circuitry to amplify the faint signals, and there are digitally processed signals -- nice square waves -- that should be easier to work with. But I never actually tried that heart code, because I ended up getting a chest band, and so now I integrate that data over bluetooth.

**Comment by MortenVinding** [comment]
Same on mine. The heart sensor board is the small one with a blop chip.
I have just captured the waveforms of both the rotations sensor and the heart sensor board.

Sorry for the pictures, but I couldn't get a output from the DSO scope.
Rotation sensor:
![tempImageeuRmCn](https://user-images.githubusercontent.com/1188091/227565890-0011e9b1-f0be-4f3e-8bd1-7f537e4ea835.gif)

Heart sensor output:
![tempImageN4kN5j](https://user-images.githubusercontent.com/1188091/227565573-65056219-a26c-44fb-bed6-6d56f10f12ef.gif)

I did try to add a LED output in the interrupt routines. Just using the build in LED, but I couldn't make it work.
Don't know why, worked fine with the simple blink sketch.

So I tried to add a serial print instead. That worked but only a few times, then the ESP crashed! No crashing without the serial.print 🤷‍♂️
But it ONLY triggered on the rising edge!

Could it be that we use some slightly different libraries?
This is the libraries I have configured in platformio.ini
        h2zero/NimBLE-Arduino@^1.4.1
        https://github.com/rpolitex/ArduinoNvs
        duinowitchery/hd44780@^1.3.2

**Comment by MortenVinding** [comment]
Ohh and don't worry about the voltages, I forgot to zero out the DSO138 (yes it's a cheap scope 😆)
They do go 0-3.3 volt (rotation) and 0-4.2 volt (heart).

**Comment by arpruss** [comment]
I wouldn't expect serial print to work inside an interrupt handler. Interrupt handlers need to move fast.

Did you configure the LED in your setup() (i.e., `pinMode(LED,OUTPUT)`)?  Then you need a bit of code like:
` static uint8_t ledState = 0; digitalWrite(LED, ledState); ledState = !ledState; `
in the ISR.

I suggest starting with putting that code right at the beginning of rotationISR();. You should only see a brief blink of the LED, because the width of the signal is narrow.

**Comment by MortenVinding** [comment]
Thank you.

Tried that but the blink on the rotation was very irregular, strange.
I tried to swap rotation and heart sensor, and on the heart sensor it seemed to blink reasonably reliable.
But at about 50% duty cycle.

That's weird because on the bluetooth the rotation is very exactly 1/2 the actual RPM.

**Comment by arpruss** [comment]
Try this. At the beginning of the ISR: digitalWrite(LED,digitalRead(rotationDetectPin)). This should exactly duplicate the rotation detect pin on the LED if both edges are being captured. If you can't tell from the LED what is going on, put the scope on the LED pin (or use a different output pin). Ideally you'd use a two-channel scope, one for the LED and the other for the rotation detect, and see if both channels are the same, but you can make-do with just one channel.

**Comment by MortenVinding** [comment]
Thanks.

That seems to work reliably. The LED is on in a little more than 3/4 of the revolution and of in little less than 1/4.
So I guess it triggers the interrupt on both edges after all?

But if I change
```
uint32_t rpm;
  uint32_t _power = _lastPower;
  if (!rev || _lastRotationDuration == 0)
    rpm = 0;
  else if (_lastRotationDuration < t - prevRotationMarker) {
    rpm = 60000 / (t - prevRotationMarker);
    _power = calculatePower(t - prevRotationMarker);
  }
  else
    rpm = 60000 / _lastRotationDuration;
```
to 120000 instead of 60000, the RPM number is exactly the same as the bike computers.

**Comment by arpruss** [comment]
I would rather figure out what is wrong than just change the timing to make it work, since even if that works for you, it won't work for others (e.g., it won't work for me).

I have two more tests for you. Comment out these lines:
```
if (t < lastBounce + rotationMarkerDebounceTime) {
    lastBounce = t;
    return;
  }
```
And see if now the timing is right. If it is, then maybe play a bit with the rotationMarkerDebounceTime and making it smaller and see if that solves your problem.

If this doesn't solve the problem, then move the LED code to right before the `uint32_t t = millis();` line and see if the LED is still blinking at the correct rate. (You should eventually be able to learn at which point in the bike pedal rotation the signal is sent, by the way.)

**Comment by MortenVinding** [comment]
Absolutely agree.
It was only to explain that the RPM number is exactly half of the real.

I tried removing the `(t < lastBounce + rotationMarkerDebounceTime)` part but it did not change anything.
Haven't tried to put the LED code before `uint32_t t = millis();` but I did have it in the very top of the rotationISR part before.
Btw: I use the `ledPin` you have already configured in the code (that is GPIO 2 and the internal LED on my board).

I noticed that `lastBounce` is used both in `rotationISR` and `heartISR`, don't know if that's a problem.
I triede to rename it in the `rotationISR` handler, but that also didn't change anything.

Thank you so much for your help.

**Comment by arpruss** [comment]
The use of the same bounce timer is definitely an issue I should look into.

**Comment by arpruss** [comment]
lastBounce is static, so it's local to the two functions. No problem there.

Add an LED toggler at the end of rotationISR(). 
`static uint8_t ledState = 0; digitalWrite(LED, ledState); ledState = !ledState;`
Then you should have the LED toggling once per full rotation. Do you?

**Comment by MortenVinding** [comment]
> Then you should have the LED toggling once per full rotation. Do you?

I already did that per your instructions before, but I tried to move it to the bottom of the rotationISR().
And yes it toggles once per revolution. Only once.

I think there is something strange going on with the ISR, because the heartbeat is way off, but if I swap the heart and rotation input, the rotation (now triggered by the heart sensor), is also exactly half of my heart rate (as displayed by the bike computer), and the heart rate (now triggerede by the rotation sensor) is showing the same strange behaviour as when the heart sensor was connected to it.

**Comment by arpruss** [comment]
Toggling once per rotation is correct behavior. So the problem is somewhere else.

**Comment by MortenVinding** [comment]
> Toggling once per rotation is correct behavior. So the problem is somewhere else.

but I thought there was a problem with the ESP32 interrupts triggering on both the rising and falling edge?

don’t you divide by 2 in the code? (I can’t figure it out. I’m terrible programmer 🙄)

**Comment by arpruss** [comment]
Yes, the interrupt handler does trigger on rise and fall. But the following code makes sure that the fall is ignored:
```
if (cleanRotationMarkerState != defaultRotationMarkerValue)
    return; 
  // trigger on end of marker
```
Try disabling the heart code completely (comment out `#define HEART_PIN`) and see if the rotation works better.

Another thing to try. After the `rpm = 60000 / _lastRotationDuration;` line, print to serial both the rpm and _lastRotationDuration. Then using a stopwatch, rotate the pedals slowly, so that a rotation takes about three seconds. Compare the three seconds the _lastRotationDuration (which is in milliseconds).

**Comment by MortenVinding** [comment]
> Yes, the interrupt handler does trigger on rise and fall. But the following code makes sure that the fall is ignored:
 
Ahh of course!
 
> Try disabling the heart code completely (comment out `#define HEART_PIN`) and see if the rotation works better.

Tried. No change :(
 
> Another thing to try. After the `rpm = 60000 / _lastRotationDuration;` line, print to serial both the rpm and _lastRotationDuration. Then using a stopwatch, rotate the pedals slowly, so that a rotation takes about three seconds. Compare the three seconds the _lastRotationDuration (which is in milliseconds).

I added:
```
    Serial.print("RPM: ");
    Serial.println(rpm);
    Serial.print("_lastRotationDuration: ");
    Serial.println(_lastRotationDuration);
```
Pictures of output from it, from the bike computer and screenshot from Zwift.
Maybe I should try a different app?

![IMG_3897](https://user-images.githubusercontent.com/1188091/229295562-e7a0f3dc-ad18-49df-aa85-95de7903cbc2.PNG)
![tempImagegknyib](https://user-images.githubusercontent.com/1188091/229295574-d38ce00d-bc0c-47fe-8008-c06c9b6fd1a3.gif)
![tempImagevQ86Aj](https://user-images.githubusercontent.com/1188091/229295577-2d0fcb9b-8490-40fb-b23f-0a4d8a911e60.gif)

**Comment by arpruss** [comment]
So it looks like it IS correctly counting the rpm, but there is some problem in the transmission to Zwift. 

The code sends data over multiple bluetooth services: cadence, power, heart and fitness. Based on your data, I think Zwift is picking up the fitness service data. Turn off the fitness service in the code (remove the FITNESS define at the top). See what happens.

**Comment by MortenVinding** [comment]
> Turn off the fitness service in the code (remove the FITNESS define at the top). See what happens.

Wheee that was IT!!
Now the RPM is spot on!

That is so cool 💪

Unfortunately the heart rate is still too low. I will try the same with the serial debug messages on that now.

**Comment by arpruss** [comment]
There is still a bug in the fitness service, or at least a compatibility problem with Zwift.

**Comment by MortenVinding** [comment]
Ohh okay sorry…

**Comment by arpruss** [comment]
I should have read the specs more carefully. Cadence in FTMS is measured in half-units. Your 120,000 fix was basically right. I corrected this, and also improved the rounding.
